package ru.medvedev.importer.enums;

public enum VtbOpeningRequestStatus {
    inqueue,
    error,
    done,
    export_error,
    export_error_inn_duplicate,
    created,
    exported,
    closed,
    closed_liquidated,
    closed_request,
    activated,
    activated_type2,
    process_client_meeting_at_bank,
    process_client_meeting_outside_bank,
    process_metting_waiting,
    process_not_call,
    process_recall,
    process_active_stops,
    process_opening,
    process_client_info_waiting,
    created_error_invalid_region,
    created_error_bank_canceled,
    created_error_client_canceled,
    created_error_client_canceled_not_request,
    created_error_not_call,
    created_error_invalid_phone,
    created_error_duplicate,
    created_error_expired
}
