package ru.medvedev.importer.enums;

public enum WebhookStatus {

    FIXED,
    TRY_TO_CREATE_LEAD,
    TRY_TO_CREATE_LEAD_SUCCESS,
    SUCCESS,
    REJECTED,
    ERROR,
    REPEAT_FIXED,
    REPEAT_TRY_TO_CREATE_LEAD,
    REPEAT_TRY_TO_CREATE_LEAD_SUCCESS,
    REPEAT_SUCCESS,
    REPEAT_REJECTED
}
