package ru.medvedev.importer.enums;

public enum WebhookStatus {

    FIXED,
    WAIT_CHECK_LEAD_AFTER_FIXED_RESPONSE,
    TRY_TO_CREATE_LEAD,
    WAIT_CREATE_LEAD_RESPONSE,
    TRY_TO_CREATE_LEAD_CHECK,
    WAIT_CHECK_LEAD_AFTER_CREATE_RESPONSE,
    TRY_TO_CREATE_LEAD_SUCCESS,
    SUCCESS,
    REJECTED,
    ERROR,
    REPEAT_FIXED,
    REPEAT_TRY_TO_CREATE_LEAD,
    REPEAT_TRY_TO_CREATE_LEAD_SUCCESS,
    REPEAT_SUCCESS,
    REPEAT_REJECTED
}
