server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8081

feign:
  client:
    config:
      vtbOpeningApi:
        loggerLevel: full
      vtbAuth:
        loggerLevel: full
      vtbApi:
        loggerLevel: full
      skorozvon:
        loggerLevel: basic
      skorozvonAuth:
        loggerLevel: basic

logging:
  file:
    name: /opt/xlsx-importer/logs/application.log
  level:
    ru.medvedev.importer: DEBUG

spring:
  task:
    scheduling:
      pool:
        size: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/xlsx_importer_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

directory:
  upload-dir: /opt/xlsx-importer/storage

cron:
  fixed-rate-update-token: 1200000
  fixed-rate-check-xlsx-exists: 900000
  launch-file-processing: '0 * * * * *'
  ending-file-processing: '30 * * * * *'
  webhook-statistic: '0 0 19 * * *'
  tg-column-header-request: '*/3 * * * * *'
  tg-initialized-new-file: '*/3 * * * * *'
  tg-file-body-processor: '*/3 * * * * *'
  tg-file-send-to-check: '2 */1 * * * *'
  creating-request: '5 */1 * * * *'
  check-request-status-vtb: '*/35 * * * * *'
  check-request-status-opening: '*/35 * * * * *'
  tg-file-send-to-skorozvon: '10 */1 * * * *'
  webhook-from-fixed-status: '17 */1 * * * *'
  webhook-from-try-to-create-status: '30 */1 * * * *'
  webhook-from-create-success-status: '45 */1 * * * *'
  webhook-check-status: '20 */2 * * * *'
  auto-load: '0 0 3 * * *'

telegram:
  xlsx-collector:
    botName: Xlsx collector
    reconnectTimer: 10000
  notificator:
    botName: Notificator
    reconnectTimer: 10000

skorozvon:
  url: https://app.skorozvon.ru

vtb:
  url: https://gw.api.vtb.ru:443/openapi/smb/lecs/lead-impers/v1
  token-url: https://open.api.vtb.ru:443/passport/oauth2/token

vtb-opening:
  url: https://openpartners.ru/api/v2/request
  url-add-request: /add
  url-check-request-status: /status
  url-check-inn: /getduplicates