server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8081

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  file:
    name: /opt/xlsx-importer/logs/application.log
  level:
    ru.medvedev.importer: DEBUG

spring:
  datasource:
    username: postgres
    password: 2x8c63tk
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/xlsx_collector
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

directory:
  upload-dir: /opt/xlsx-importer/storage

cron:
  fixed-rate-update-token: 5400000
  fixed-rate-check-xlsx-exists: 900000

telegram:
  token: 5532430343:AAGc7aigR7QcWjprSB5grbfeFDEaTd0KDlw
  botName: Xlsx collector
  reconnectTimer: 10000

skorozvon:
  url: https://app.skorozvon.ru
  application-key: 172f48c27f7eb1c2322526b8f92d5b25dcc9cbc8785f137a428795b3f4a4cb2a
  api-key: 4ba9211e35ec615a05e9ce04ebf78e837f72b03b236b98de8c6389358016df46
  application-id: 29055bf486467ffb99159edf3c21881d8ec4349ee1eb61c0b172364bbcc623b7
  login: wfactorysales@gmail.com

vtb:
  url: https://epa.api.vtb.ru/openapi/smb/lecs
  token-url: https://passport.api.vtb.ru/passport/oauth2/token
  client-id: f3007ea97a8bc1f37d3366c9e4f2f836
  client-secret: 916d1cf1d007d7dfb21f6a27cd99c5f1