directory:
  upload-dir: D:/xlsx-storage

spring:
  datasource:
    username: postgres
    password: 2x8c63tk
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/xlsx_collector

telegram:
  token: 5453887520:AAHjc3J05rXIY3ulwhXdqMtUQ3KrIutyFdo