server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8081

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  file:
    name: /opt/xlsx-importer/logs/application.log
  level:
    ru.medvedev.importer: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/xlsx_importer_db
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

directory:
  upload-dir: /opt/xlsx-importer/storage

cron:
  fixed-rate-update-token: 1200000
  fixed-rate-check-xlsx-exists: 900000
  launch-file-processing: '0 * * * * *'
  webhook-statistic: '0 0 19 * * *'
  tg-column-header-request: '*/3 * * * * *'
  tg-initialized-new-file: '*/3 * * * * *'
  tg-file-body-processor: '*/3 * * * * *'
  webhook-change-status: '17 */1 * * * *'
  auto-load: '0 0 3 * * *'

telegram:
  xlsx-collector:
    botName: Xlsx collector
    reconnectTimer: 10000
  notificator:
    botName: Notificator
    reconnectTimer: 10000

skorozvon:
  url: https://app.skorozvon.ru

vtb:
  url: https://epa.api.vtb.ru/openapi/smb/lecs
  token-url: https://passport.api.vtb.ru/passport/oauth2/token

vtb-opening:
  url: https://openpartners.ru/api/v2/request
  url-add-request: /add
  url-check-request-status: /status
  url-check-inn: /getduplicates